# Generated by Django 3.0.3 on 2020-06-05 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('Djapp', '0002_auto_20200605_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='books',
            name='publisher',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
