# Generated by Django 3.0.3 on 2020-06-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Djapp', '0003_auto_20200605_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='file',
            field=models.FileField(upload_to='files/'),
        ),
    ]
