# Generated by Django 3.0.3 on 2020-06-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Djapp', '0005_auto_20200605_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='publisher',
        ),
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='books',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
